package miniJava.SyntacticAnalyzer;

public enum TokenKind {NUM, CLASS, ID, LBRACKET, RBRACKET, VOID, LPAREN, RPAREN, EOT, EQUAL, THIS,
							PUBLIC, PRIVATE, STATIC, INT, BOOLEAN, COMMA, DOT, RETURN, SEMICOLON,
								IF, ELSE, WHILE, TRUE, FALSE, NEW, LCURLY, RCURLY,
								OR, AND, ISEQUAL, NOTEQUAL, LT, GT, LTE, GTE, PLUS, MINUS, TIMES, DIVIDE, EXCLA,
									ERROR}

